# Generated by Django 3.0.2 on 2020-02-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='first name*')),
                ('lastname', models.CharField(max_length=100, verbose_name='last name*')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail:')),
                ('num_of_ppl', models.CharField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six')], max_length=6)),
                ('comment', models.CharField(max_length=10000, verbose_name='comment*')),
            ],
        ),
    ]
