# Generated by Django 3.0.2 on 2020-02-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200206_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_approved', models.BooleanField(null=True, verbose_name='Approved')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Reservations')),
            ],
        ),
    ]
