# Generated by Django 3.0.2 on 2020-02-07 16:08

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000, verbose_name='comment*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2020, 2, 7, 16, 8, 17, 234540, tzinfo=utc), max_length=100, verbose_name='first name*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='last name*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='num_of_ppl',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six')], max_length=6),
        ),
    ]
