# Generated by Django 3.0.2 on 2020-02-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200207_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='comment',
            field=models.CharField(max_length=10000, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
    ]
