# Generated by Django 3.0.2 on 2020-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200212_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='stay_approved',
            field=models.BooleanField(default=False, null=True, verbose_name='Approved'),
        ),
        migrations.DeleteModel(
            name='Approved',
        ),
    ]
