# Generated by Django 3.0.3 on 2020-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200212_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
