# Generated by Django 3.0.3 on 2020-02-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20200213_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date of application'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date out'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='num_of_ppl',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], max_length=6, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date in'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='stay_approved',
            field=models.BooleanField(default=False, null=True, verbose_name='approved'),
        ),
    ]
