# Generated by Django 3.0.3 on 2020-02-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0010_auto_20200213_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tennants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationsAccepted', models.ManyToManyField(to='booking.Reservations')),
            ],
        ),
    ]
